/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.CategoryBean;
import com.geeks.beans.UserBean;
import com.geeks.dao.CategoryDAO;
import com.geeks.dao.UserDAO;
import com.geeks.daoImp.CategoryDAOImpl;
import com.geeks.daoImp.UserDAOImp;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class CategoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserDAO
     */
    public CategoryFrame() throws SQLException {
        initComponents();
        setTable();
        setButtons(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCategoryName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategoryFrame = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCategoryName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 320, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Category name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 290, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Description");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 220, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 150, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 150, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 150, -1));

        tableCategoryFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableCategoryFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategoryFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryFrameMouseClicked(evt);
            }
        });
        tableCategoryFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableCategoryFrameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategoryFrame);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 1300, 260));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 180, -1));

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtAreaDescription.setRows(5);
        jScrollPane2.setViewportView(txtAreaDescription);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 320, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1430, 740));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Category Panel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(2);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tableCategoryFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryFrameMouseClicked
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableCategoryFrameMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        setButtons(2);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(3);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableCategoryFrameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableCategoryFrameKeyReleased
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableCategoryFrameKeyReleased

    private void setButtons(int val){
        if(val==1){
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }
    
    public void setAllTxts() {
        setButtons(1);
        int id = (int) tableCategoryFrame.getValueAt(tableCategoryFrame.getSelectedRow(), 0);
        CategoryBean categoryBean = new CategoryBean();
        categoryBean.setCategoryiD(id);
        
        CategoryDAO categoryDAO = new CategoryDAOImpl();
        ArrayList<CategoryBean> list = (ArrayList<CategoryBean>) categoryDAO.setAllTxt(categoryBean);
        for (CategoryBean categoryBean1 : list) {
            txtCategoryName.setText(categoryBean1.getCategoryName());
            txtAreaDescription.setText(categoryBean1.getDescription());
        }
    }
    private void clearAll() {
        txtCategoryName.setText("");
        txtAreaDescription.setText("");
    }
    
    public void setTable() throws SQLException {
        CategoryDAO categoryDAO = new CategoryDAOImpl();
        tableCategoryFrame.setModel(buildTableModel(categoryDAO.viewAllCategoryResultSet()));
    }

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    public void addForOneUpdateForTwo(int one) {
        String categoryName = txtCategoryName.getText();
        String description = txtAreaDescription.getText();

        int createdBy = UserDAOImp.userId;
    
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String currentDate = df.format(d);

        CategoryBean categoryBean = new CategoryBean();
        categoryBean.setCategoryName(categoryName);
        categoryBean.setDescription(description);
           
        CategoryDAO categoryDAO = new CategoryDAOImpl();
        if (one == 1) {
            if (categoryDAO.checkCategory(categoryBean)) {
                JOptionPane.showMessageDialog(this, "Category already exits!");
            } else {
                categoryBean.setCreatedBy(createdBy);
                categoryBean.setCreatedDate(currentDate);
                
                if (categoryDAO.addCategoryDetails(categoryBean) != 0) {
                    try {
                        clearAll();
                        setTable();
                        JOptionPane.showMessageDialog(this, "Category added successfully!");
                    } catch (SQLException ex) {
                        Logger.getLogger(CategoryFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the category!");
                }
            }
        } else if(one==2) {
            int id = (int) tableCategoryFrame.getValueAt(tableCategoryFrame.getSelectedRow(), 0);
            
            categoryBean.setModifiedBy(createdBy);
            categoryBean.setModifiedDate(currentDate);
            categoryBean.setCategoryiD(id);
            
            if (categoryDAO.updateCategoryDetails(categoryBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "Category updated successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(CategoryFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the category!");
            }
        }else if(one==3){
                int id = (int) tableCategoryFrame.getValueAt(tableCategoryFrame.getSelectedRow(), 0);
                categoryBean.setCategoryiD(id);
                if (categoryDAO.deleteCategoryDetails(categoryBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "Category deleted successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(CategoryFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the category!");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CategoryFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CategoryFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCategoryFrame;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextField txtCategoryName;
    // End of variables declaration//GEN-END:variables

}
