/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.OrderBean;
import com.geeks.dao.OrderDAO;
import com.geeks.dao.OrderDetailsDAO;
import com.geeks.daoImp.OrderDAOImpl;
import com.geeks.daoImp.OrderDetailsDAOImpl;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class HotelSales extends javax.swing.JFrame {

    /**
     * Creates new form HotelSales
     */
    public static String order="",paid="";
    
    public HotelSales() throws SQLException {
        initComponents();
        setOrderTable();
    }
    
    private void setOrderTable() throws SQLException{
        OrderDAO orderDAO = new OrderDAOImpl();
        String order = txtOrderNo.getText();
        OrderBean orderBean = new OrderBean();
        orderBean.setOrderNumber(order);
        tableOrder.setModel(buildTableModel(orderDAO.viewAllOrderResultSet(orderBean)));
        setOrderDetailsTable();
    }
    
    private void setOrderDetailsTable() throws SQLException{
        if(tableOrder.isCellSelected(tableOrder.getSelectedRow(), tableOrder.getSelectedRow())){
            String order = (String) tableOrder.getValueAt(tableOrder.getSelectedRow(), 1);
            OrderDetailsDAO orderDetailsDAO = new OrderDetailsDAOImpl();
            tableOrderDetails.setModel(buildTableModel(orderDetailsDAO.viewAllOrderDetailsBeanResultSet2(order)));
        }
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderDetails = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrder = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtOrderNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1800, 860));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableOrderDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOrderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderDetailsMouseClicked(evt);
            }
        });
        tableOrderDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableOrderDetailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableOrderDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 1100, 660));

        tableOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOrderMouseClicked(evt);
            }
        });
        tableOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableOrderKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tableOrder);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 630, 510));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Order No.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 190, 40));

        txtOrderNo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtOrderNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderNoKeyReleased(evt);
            }
        });
        jPanel1.add(txtOrderNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 270, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Order Details Panel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 180, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 180, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1776, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableOrderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderDetailsMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableOrderDetailsMouseClicked

    private void tableOrderDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableOrderDetailsKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tableOrderDetailsKeyReleased

    private void getAllOrder(){
        String order = (String) tableOrder.getValueAt(tableOrder.getSelectedRow(), 1);
        OrderDetailsDAO orderDetailsDAO = new OrderDetailsDAOImpl();
        try {
            tableOrderDetails.setModel(buildTableModel(orderDetailsDAO.viewAllOrderDetailsBeanResultSet2(order)));
        } catch (SQLException ex) {
            Logger.getLogger(HotelSales.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtOrderNo.setText(order);
    }
    private void tableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOrderMouseClicked
        // TODO add your handling code here:
        getAllOrder();
    }//GEN-LAST:event_tableOrderMouseClicked

    private void tableOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableOrderKeyReleased
        getAllOrder();
    }//GEN-LAST:event_tableOrderKeyReleased

    
    private void txtOrderNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrderNoKeyReleased
        try {
            // TODO add your handling code here:
            setOrderTable();
        } catch (SQLException ex) {
            Logger.getLogger(HotelSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtOrderNoKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String ord = (String) tableOrder.getValueAt(tableOrder.getSelectedRow(), 1);
        BigDecimal pay = (BigDecimal) tableOrder.getValueAt(tableOrder.getSelectedRow(), 5);
        order = ord;
        paid = pay.toString();
        txtOrderNo.setText(ord);
        this.dispose();
        OrderFrame of;
        try {
            of = new OrderFrame();
            of.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(HotelSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String order = (String) tableOrder.getValueAt(tableOrder.getSelectedRow(), 1);
        OrderBean orderBean = new OrderBean();
        orderBean.setOrderNumber(order);
        OrderDAO orderDAO = new OrderDAOImpl();
        orderDAO.deleteOrderDetails(orderBean);
        try {
            txtOrderNo.setText("");
            setOrderTable();
        } catch (SQLException ex) {
            Logger.getLogger(HotelSales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HotelSales().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(HotelSales.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableOrder;
    private javax.swing.JTable tableOrderDetails;
    private javax.swing.JTextField txtOrderNo;
    // End of variables declaration//GEN-END:variables
}
