/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.CategoryBean;
import com.geeks.beans.ProductBean;
import com.geeks.dao.CategoryDAO;
import com.geeks.dao.ProductDAO;
import com.geeks.daoImp.CategoryDAOImpl;
import com.geeks.daoImp.ProductDAOImpl;
import com.geeks.daoImp.UserDAOImp;
import com.geeks.utils.BarCodeGenerator;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class ProductFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserDAO
     */
    public ProductFrame() throws SQLException {
        initComponents();
        setComboCategory();
        setTable();
        setBarCode();
        setButtons(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtProductName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductFrame = new javax.swing.JTable();
        txtQuatity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBarCode = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProductName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 160, 320, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Product name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 220, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("Category");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 230, 40));

        txtPrice.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 230, 320, -1));

        txtSize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 300, 320, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Packing size");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 220, 40));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 510, 150, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 510, 150, -1));

        tableProductFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableProductFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProductFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductFrameMouseClicked(evt);
            }
        });
        tableProductFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableProductFrameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductFrame);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 970, 450));

        txtQuatity.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtQuatity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 370, 320, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, 220, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Bar Code");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, 230, 40));

        lblBarCode.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblBarCode.setText("            Image");
        jPanel2.add(lblBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 440, 320, 40));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 150, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton2.setText("< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("Retail Price");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 230, 40));

        comboCategory.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 100, 320, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1640, 740));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Product Panel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setBarCode(){
        String bar = BarCodeGenerator.generator();
        ProductDAO productDAO = new ProductDAOImpl();
        if(productDAO.checkBarCode().contains(bar)){
            setBarCode();
        }else{
            lblBarCode.setText(bar);
        }
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            addForOneUpdateForTwo(1);
        } catch (SQLException ex) {
            Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableProductFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductFrameMouseClicked
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableProductFrameMouseClicked

    private void tableProductFrameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableProductFrameKeyReleased
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableProductFrameKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // TODO add your handling code here:
            addForOneUpdateForTwo(2);
        } catch (SQLException ex) {
            Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // TODO add your handling code here:
            addForOneUpdateForTwo(3);
        } catch (SQLException ex) {
            Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        setButtons(2);
    }//GEN-LAST:event_jPanel2MouseClicked

    public void setAllTxts() {
        setButtons(1);
        int id = (int) tableProductFrame.getValueAt(tableProductFrame.getSelectedRow(), 0);
        ProductBean productBean = new ProductBean();
        productBean.setProductID(id);
        
        ProductDAO productDAO = new ProductDAOImpl();
        ArrayList<ProductBean> list = (ArrayList<ProductBean>) productDAO.setAllTxt(productBean);
        for (ProductBean productBean1 : list) {
            txtProductName.setText(productBean1.getProductName());
            comboCategory.setSelectedItem(productBean1.getCategoryBean().getCategoryName());
            txtPrice.setText(String.valueOf(productBean1.getPrice()));
            txtQuatity.setText(String.valueOf(productBean1.getQuantity()));
            txtSize.setText(productBean1.getSize());
            lblBarCode.setText(productBean1.getBarcode());
        }
    }
    
    private void clearAll(){
        txtProductName.setText("");
        comboCategory.setSelectedIndex(0);
        txtPrice.setText("");
        txtQuatity.setText("");
        txtSize.setText("");
    }
    
    private void setButtons(int val){
        if(val==1){
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }
    
    public void setTable() throws SQLException {
        ProductDAO categoryDAO = new ProductDAOImpl();
        tableProductFrame.setModel(buildTableModel(categoryDAO.viewAllProductResultSet()));
    }

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    public void addForOneUpdateForTwo(int one) throws SQLException {
        String productName = txtProductName.getText();
        String categoryName = comboCategory.getSelectedItem().toString();
        String n=txtPrice.getText();
        
        float price = 0;
        if(n.equals("")){
            price = 0;
        }else{
            price = Float.parseFloat(n);
        }
        
        String size = txtSize.getText();
        String barcode = lblBarCode.getText();
         
        String p = txtQuatity.getText();
        int quantity=0;
        if(p.equals("")){
            quantity = 0;
        }else{
            quantity = Integer.parseInt(p);
        }
        
        int createdBy = UserDAOImp.userId;
    
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String currentDate = df.format(d);

        ProductBean productBean = new ProductBean();
        productBean.setProductName(productName);
            CategoryBean categoryBean = new CategoryBean();
            categoryBean.setCategoryName(categoryName);
        ProductDAO productDAO = new ProductDAOImpl();
            int categoryId = productDAO.getIdByCategory(categoryBean);
            categoryBean.setCategoryiD(categoryId);
        
        productBean.setCategoryBean(categoryBean);
        
        productBean.setPrice(price);
        productBean.setSize(size);
        productBean.setQuantity(quantity);
        setBarCode();
        productBean.setBarcode(barcode);
       
        if (one == 1) {
            if (productDAO.checkProduct(productBean)) {
                JOptionPane.showMessageDialog(this, "Product already exits!");
            } else {
                productBean.setCreatedBy(createdBy);
                productBean.setCreatedDate(currentDate); 
                if (productDAO.addProductDetails(productBean) != 0) {
                clearAll();
                setTable();
                JOptionPane.showMessageDialog(this, "Product added successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the product!");
                } 
            }  
        } else if(one==2) {
            int id = (int) tableProductFrame.getValueAt(tableProductFrame.getSelectedRow(), 0);
            
            productBean.setModifiedBy(createdBy);
            productBean.setModifiedDate(currentDate);
            productBean.setProductID(id);
            
            if (productDAO.updateProductDetails(productBean) != 0) {
                clearAll();
                setTable();
                setButtons(2);
                JOptionPane.showMessageDialog(this, "Product updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the product!");
            }
        }else if(one==3){
                int id = (int) tableProductFrame.getValueAt(tableProductFrame.getSelectedRow(), 0);
                productBean.setProductID(id);
                if (productDAO.deleteProductDetails(productBean) != 0) {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "Product deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the product!");
            }
        }
    }
    
    public void setComboCategory(){
        ProductDAO productDAO = new ProductDAOImpl();
        List<String> li = productDAO.viewAllCategory();
        comboCategory.addItem("Select one");
        for(String s : li){
            comboCategory.addItem(s);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboCategory;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBarCode;
    private javax.swing.JTable tableProductFrame;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtQuatity;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
