/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.geeks.frames;

import com.geeks.beans.AccountBean;
import com.geeks.beans.ProductBean;
import com.geeks.beans.StockBean;
import com.geeks.beans.UserBean;
import com.geeks.dao.ProductDAO;
import com.geeks.dao.StockDAO;
import com.geeks.dao.UserDAO;
import com.geeks.daoImp.ProductDAOImpl;
import com.geeks.daoImp.StockDAOImpl;
import com.geeks.daoImp.UserDAOImp;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xyz
 */
public class StockFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserDAO
     */
    public StockFrame() throws SQLException {
        initComponents();
        setTable();
        setButtons(2);
        setComboAccount();
        setComboProduct();
        clearAll();
    }

    private void setComboAccount(){
        comboAccount.removeAllItems();
        StockDAO stockDAO = new StockDAOImpl();
        List<String> li = stockDAO.viewAllAccount();
        comboAccount.addItem("Select one");
        for(String s : li){
            comboAccount.addItem(s);
        }
    }
    
    private void setComboProduct(){
        comboProduct.removeAllItems();
        StockDAO stockDAO = new StockDAOImpl();
        List<String> li = stockDAO.viewAllProduct();
        comboProduct.addItem("Select one");
        for(String s : li){
            comboProduct.addItem(s);
        }
    }
    
    public void setTable() throws SQLException {
        StockDAO stockDAO = new StockDAOImpl();
        tableStockFrame.setModel(buildTableModel(stockDAO.viewAllStockResultSet()));
    }

    public static DefaultTableModel buildTableModel(ResultSet rs) throws SQLException {
        ResultSetMetaData metaData = rs.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtStock = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtWSP = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStockFrame = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        comboAccount = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        comboDay = new javax.swing.JComboBox();
        comboMon = new javax.swing.JComboBox();
        comboYear = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        comboProduct = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txtRP = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStock.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 170, 270, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Stock");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 170, 220, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("Dealer");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 230, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 240, 290, 40));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 240, 270, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Retail Price");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 280, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("Whole Sale Price");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, 290, 40));

        txtWSP.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtWSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 310, 270, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 630, 180, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 180, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, 180, -1));

        tableStockFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableStockFrame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableStockFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStockFrameMouseClicked(evt);
            }
        });
        tableStockFrame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableStockFrameKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableStockFrame);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1080, 470));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton4.setText("< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 180, -1));

        comboAccount.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        comboAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAccountActionPerformed(evt);
            }
        });
        jPanel2.add(comboAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 30, 270, 40));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 630, 180, -1));

        comboDay.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel2.add(comboDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 460, 70, 40));

        comboMon.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        comboMon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel2.add(comboMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 460, 80, 40));

        comboYear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        comboYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2019", "2020", "2021", "2022", "2023" }));
        jPanel2.add(comboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 460, 100, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("Purchase date");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 460, 280, 40));

        comboProduct.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        comboProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductActionPerformed(evt);
            }
        });
        jPanel2.add(comboProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 100, 270, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setText("Product");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 100, 140, 40));

        txtRP.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(txtRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 380, 270, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Want to add?");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 30, 160, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Want to add?");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 100, 160, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1700, 740));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Stock Panel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addForOneUpdateForTwo(int one) {
        String stock = txtStock.getText();
        String dealer = comboAccount.getSelectedItem().toString();
        String product = comboProduct.getSelectedItem().toString();
        String WSP = txtWSP.getText();
        //String RP = txtRP.getText();
        
      
        String p = txtQuantity.getText();
        int quantity=0;
        if(p.equals("")){
            quantity = 0;
        }else{
            quantity = Integer.parseInt(p);
        }
        
        String r = txtRP.getText();
        float RP=0;
        if(r.equals("")){
            RP = 0;
        }else{
            RP = Float.parseFloat(r);
        }
        
        String day = comboDay.getSelectedItem().toString();
        int mon = comboMon.getSelectedIndex() + 1;
        String m = mon + "";
        if (mon < 10) {
            m = "0" + mon;
        }

        String year = comboYear.getSelectedItem().toString();
        String purchaseDate = year + "-" + m + "-" + day;

        int createdBy = UserDAOImp.userId;

        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String currentDate = df.format(d);

        StockBean stockBean = new StockBean();
        stockBean.setStock(stock);
        StockDAO stockDAO = new StockDAOImpl();
            AccountBean accountBean = new AccountBean();
            accountBean.setAccountName(dealer);
        int accountId = stockDAO.getIdByAccount(accountBean);
            accountBean.setAccountId(accountId);
        
            ProductBean productBean = new ProductBean();
            productBean.setProductName(product);
        int productId = stockDAO.getIdByProduct(productBean);
            productBean.setProductID(productId);
        
        stockBean.setAccountBean(accountBean);
        stockBean.setProductBean(productBean);
        stockBean.setQuantity(quantity);
        stockBean.setRP(RP);
        stockBean.setWSP(WSP);
        stockBean.setDate(purchaseDate);
        
        if (one == 1) {
            if (stockDAO.checkStock(stockBean)) {
                JOptionPane.showMessageDialog(this, "Stock name already exits!");
            } else {
                stockBean.setCreatedBy(createdBy);
                stockBean.setCreatedDate(currentDate);
                
                if (stockDAO.addStockDetails(stockBean) != 0) {
                    try {
                        clearAll();
                        setTable();
                        //start updating product
                        stockBean.setQuantity(quantity+StockDAOImpl.setQuantity);
                        stockBean.setRP(RP);
                        //stockBean.setProductBean(productBean);
                        if(stockDAO.updateProductByStock(stockBean)!=0){
                            JOptionPane.showMessageDialog(this, "Added Done");
                        }else{
                            JOptionPane.showMessageDialog(this, "Failed");
                        }
                        //end updating product
                        JOptionPane.showMessageDialog(this, "Stock added successfully!");
                    } catch (SQLException ex) {
                        Logger.getLogger(StockFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to add the stock!");
                }
            }
        } else if(one==2) {
            int id = (int) tableStockFrame.getValueAt(tableStockFrame.getSelectedRow(), 0);
            
            stockBean.setModifiedBy(createdBy);
            stockBean.setModifiedDate(currentDate);
            stockBean.setStockID(id);
            
            if (stockDAO.updateStockDetails(stockBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    //start updating product
                        stockBean.setQuantity(StockDAOImpl.setQuantity-quantity);
                        stockBean.setRP(RP);
                        //stockBean.setProductBean(productBean);
                        if(stockDAO.updateProductByStock(stockBean)!=0){
                            JOptionPane.showMessageDialog(this, "Updated Done");
                        }else{
                            JOptionPane.showMessageDialog(this, "Failed");
                        }
                    //end updating product
                    JOptionPane.showMessageDialog(this, "Stock updated successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(StockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update the stock!");
            }
        }else if(one==3){
                int id = (int) tableStockFrame.getValueAt(tableStockFrame.getSelectedRow(), 0);
                stockBean.setStockID(id);
                if (stockDAO.deleteStockDetails(stockBean) != 0) {
                try {
                    clearAll();
                    setTable();
                    setButtons(2);
                    JOptionPane.showMessageDialog(this, "Stock deleted successfully!");
                } catch (SQLException ex) {
                    Logger.getLogger(StockFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the user!");
            }
        }
    }
    
    private void updateProductByStock(){
        String product = comboProduct.getSelectedItem().toString();
        StockDAO stockDAO = new StockDAOImpl();
        StockBean stockBean = new StockBean();
        ProductBean productBean = new ProductBean();
            productBean.setProductName(product);
        int productId = stockDAO.getIdByProduct(productBean);
            productBean.setProductID(productId);
        stockBean.setProductBean(productBean);
        if(stockDAO.updateProductByStock(stockBean)==1){
            JOptionPane.showMessageDialog(this, "Done");
        }else{
            JOptionPane.showMessageDialog(this, "Failed");
        }
         
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(1);
    }//GEN-LAST:event_btnAddActionPerformed

    private void tableStockFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStockFrameMouseClicked
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableStockFrameMouseClicked

    private void tableStockFrameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableStockFrameKeyReleased
        // TODO add your handling code here:
        setAllTxts();
    }//GEN-LAST:event_tableStockFrameKeyReleased

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
       setButtons(2);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseClicked

    public void clearAll() {
        txtStock.setText("");
        comboAccount.setSelectedIndex(0);
        comboProduct.setSelectedIndex(0);
        txtQuantity.setText("");
        txtWSP.setText("");
        txtRP.setText("");
       
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat();
        df.applyPattern("yyyy-MM-dd");

        String date[] = df.format(d1).split("-");
        comboDay.setSelectedItem(date[2]);
        comboMon.setSelectedIndex(Integer.parseInt(date[1]) - 1);
        comboYear.setSelectedItem(date[0]);
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(2);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        addForOneUpdateForTwo(3);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAccountActionPerformed
        // TODO add your handling code here:
        //setComboAccount();
    }//GEN-LAST:event_comboAccountActionPerformed

    private void comboProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductActionPerformed
        // TODO add your handling code here:
        //setComboProduct();
    }//GEN-LAST:event_comboProductActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            AccountsFrame a = new AccountsFrame();
            a.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(StockFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            ProductFrame p = new ProductFrame();
            p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(StockFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void setButtons(int val){
        if(val==1){
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }else{
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }
    
    public void setAllTxts() {
        setButtons(1);
        int id = (int) tableStockFrame.getValueAt(tableStockFrame.getSelectedRow(), 0);
        StockBean stockBean = new StockBean();
        stockBean.setStockID(id);
        StockDAO stockDAO = new StockDAOImpl();
        ArrayList<StockBean> list = (ArrayList<StockBean>) stockDAO.setAllTxt(stockBean);
        for (StockBean s : list) {
            txtStock.setText(s.getStock());
            comboAccount.setSelectedItem(s.getAccountBean().getAccountName());
            comboProduct.setSelectedItem(s.getProductBean().getProductName());
            txtQuantity.setText(String.valueOf(s.getQuantity()));
            txtWSP.setText(s.getWSP());
            txtRP.setText(String.valueOf(s.getRP()));
            String date[] = s.getDate().split("-");
            comboDay.setSelectedItem(date[2]);
            comboMon.setSelectedIndex(Integer.parseInt(date[1]) - 1);
            comboYear.setSelectedItem(date[0]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox comboAccount;
    private javax.swing.JComboBox comboDay;
    private javax.swing.JComboBox comboMon;
    private javax.swing.JComboBox comboProduct;
    private javax.swing.JComboBox comboYear;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableStockFrame;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRP;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtWSP;
    // End of variables declaration//GEN-END:variables

    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
